apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tf-admin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tf-admin
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-admin
---
apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
spec:
  template:
    spec:
      containers:
      - name: terraform
        image: shiveshabhishek/tf-pod-create-job:v1
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"] # Use shell to chain multiple commands
        args:
          - terraform init &&
            terraform apply -auto-approve
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube/
          subPath: kubeconfig
      restartPolicy: Never
      volumes:
      - name: kubeconfig
        configMap:
          name: kubeconfig-configmap
      serviceAccountName: tf-admin
